dataset_source: office31_amazon
dataset_target: office31_dslr
model: clcd_14_7x2_224
chans: 3
num_classes: 31
img_size: 224
interpolation: bicubic
train_interpolation: random
amp: True
source_batch_size: 32
target_batch_size: 32
validation_batch_size: 32
lr: 5e-5
min_lr: 1e-6
sched: cosine
epochs: 100
cooldown_epochs: 25
warmup_epochs: 25
warmup_lr: 1e-5
opt: adamw
workers: 2
pretrained: False
tasks: 6
memory_size: 1000
log_wandb: False