experiment: usps_to_mnist
dataset_source: usps
dataset_target: mnist
num_classes: 10
img_size: 32
mean_source:
    - 0.2469
std_source:
    - 0.2989
mean_target:
    - 0.1307
std_target:
    - 0.3081
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
amp: True
batch_size: 100
lr: 55e-5
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 300
warmup_epochs: 10
center_aware_epochs: 10
warmup_lr: 0.00001
opt: adamw
workers: 2
no_aug: True