dataset_source: usps
dataset_target: mnist
model: cct_7_7x2_28
chans: 1
num_classes: 10
img_size: 28
mean_source:
    - 0.2469
std_source:
    - 0.2989
mean_target:
    - 0.1307
std_target:
    - 0.3081
interpolation: bicubic
train_interpolation: random
amp: True
source_batch_size: 64
target_batch_size: 64
validation_batch_size: 128
lr: 5e-5
min_lr: 1e-6
sched: cosine
epochs: 50
cooldown_epochs: 10
warmup_epochs: 25
warmup_lr: 1e-5
opt: adamw
workers: 2
tasks: 5
memory_size: 1000
log_wandb: False