dataset_source: visda
dataset_target: visda
model: cct_7_7x2_224
log_wandb: False
num_classes: 12
img_size: 224
interpolation: bicubic
train_interpolation: random
amp: True
source_batch_size: 64
target_batch_size: 64
validation_batch_size: 128
lr: 5e-5
min_lr: 1e-6
sched: cosine
epochs: 125
cooldown_epochs: 10
warmup_epochs: 25
warmup_lr: 1e-5
opt: adamw
workers: 2