dataset_source: visda
dataset_target: visda
model: cct_14_7x2_224
log_wandb: True
num_classes: 12
img_size: 224
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
# mixup: 0.8
# mixup_off_epoch: 0
# mixup_prob: 1.0
# mixup_mode: batch
# mixup_switch_prob: 0.5
# cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
source_batch_size: 32
target_batch_size: 128
validation_batch_size: 128
lr: 5e-6
min_lr: 1e-8
sched: cosine
epochs: 300
cooldown_epochs: 10
warmup_epochs: 0
warmup_lr: 1e-5
opt: adamw
# smoothing: 0.1
workers: 2
pretrained: True